pool:
  vmImage: ubuntu-latest

variables:
  major: 8
  minor: 0
  buildOffset: 0
  packageName: 'Codeworx.Core'
  projects: 'src/Codeworx.Primitives;src/Codeworx.Core;src/Codeworx.AspNetCore;src/Codeworx.AspNetCore.Authentication.Introspection'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: "Install package-version tool"
  inputs:
    command: 'custom'
    custom: 'tool'
    arguments: 'install Codeworx.PackageVersion -g'

- task: DotNetCoreCLI@2
  displayName: "Get next PackageVersion"
  inputs:
    command: 'custom'
    custom: 'package-version'
    arguments: '$(packageName) -m $(major) -n $(minor) -b $(buildOffset) -o DevOps -p $(prerelease)'

- task: Bash@3
  displayName: "Update build version"
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      echo '##vso[build.updatebuildnumber]$(PackageVersion)'

- task: DownloadSecureFile@1
  displayName: Download signing key
  inputs:
    secureFile: 'core_signkey.snk'

- task: CopyFiles@2
  displayName: copy signing key
  inputs:
    SourceFolder: '$(Agent.TempDirectory)'
    Contents: 'core_signkey.snk'
    TargetFolder: './private'

- task: DotNetCoreCLI@2
  displayName: "run dotnet pack"
  inputs:
    command: 'pack'
    packagesToPack: '$(projects)'
    configuration: '$(buildConfiguration)'
    versioningScheme: 'off'
    buildProperties: 'Version=$(PackageVersion);FileVersion=$(PackageVersionFileVersion);AssemblyVersion=$(major).0.0.0;SignAssembly=true;AssemblyOriginatorKeyFile=..\..\private\core_signkey.snk'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
